/*
 * This file was generated by swagger-genereator
 * Do not modify this file manually.
 * Version: 1.0.0
 * Title: Uber API
 * Description: Move your app forward with the Uber API
 * Author: Muhtalip Dede
 * Generated on: 2024-05-18 */

import axios from 'axios';

axios.defaults.baseURL = 'https://api.uber.com/v1';

import { PriceEstimate } from './interfaces/PriceEstimate';
import { Product } from './interfaces/Product';
import { Activity } from './interfaces/Activity';
import { Profile } from './interfaces/Profile';
import { Error } from './interfaces/Error';
import { Activities } from './interfaces/Activities';

export async function getEstimatesPrice(config?: any): Promise<any> {
    const response = await axios.get(`/estimates/price`, config);
    return response.data;
}

export async function getProducts(config?: any): Promise<any> {
    const response = await axios.get(`/products`, config);
    return response.data;
}

export async function getMe(config?: any): Promise<Profile> {
    const response = await axios.get(`/me`, config);
    return response.data;
}

export async function getHistory(config?: any): Promise<Activities> {
    const response = await axios.get(`/history`, config);
    return response.data;
}

export async function getEstimatesTime(config?: any): Promise<any> {
    const response = await axios.get(`/estimates/time`, config);
    return response.data;
}

