/*
 * This file was generated by swagger-genereator
 * Do not modify this file manually.
 * Version: 1.0.0
 * Title: Uber API
 * Description: Move your app forward with the Uber API
 * Author: Muhtalip Dede
 * Generated on: 2024-05-18 */

export interface PriceEstimate {
    surge_multiplier: any;
    product_id: string;
    estimate: string;
    display_name: string;
    low_estimate: any;
    currency_code: string;
    high_estimate: any;
}
